App:
  Host: "localhost"
  Port: "8080"
Mongo:
  Uri: mongodb://localhost:27017
  DbName: zkoj
Judge:
  Type: LocalJudge
  Java:
    JDK11:
      BaseArgs: "C:\\Program Files\\Java\\jdk-11.0.1\\bin\\java.exe"
      Env: "PATH=C:\\Program Files\\Java\\jdk-11.0.1\\bin"
Sandbox:
  Url: "http://localhost:5050/run"
  Method: "POST"